### PR TITLE
Add support for IE 9

### PR DESCRIPTION
**Pull request by dhenson02**
IE 9 doesn't include support for element.classList so check for / replace it as needed.

http://caniuse.com/#feat=classlist

### CODE REVIEW

**Comment by terwanerik** [comment]
Thanks for this! So the script, with these changes, now works in IE9?

**Comment by dhenson02** [comment]
The RAF check you do in one spot is not done in the other and that may fail as well.  I don't see any other incompatibilities in the rest of the code but I don't have IE 9 to test it outright.  

I'll make another commit in a little bit with that change

**Comment by dhenson02** [comment]
I would also recommend (somewhat unrelated to this) to use [fastdom](https://github.com/wilsonpage/fastdom) for the RAF usage but it isn't strictly necessary.

**Comment by terwanerik** [comment]
Ah yes that RAF check was still in the `init()` function because i used to use .onscroll as a fallback method, and that was linked to the `scrollElement` which was null before init() was called. I'll merge this and remove the RAF check in the init() function.

**Comment by terwanerik** [comment]
Updated to v0.2.6 with the fallback. Thanks for the input!

**Pull request merged**
