### PR TITLE
Added UMD wrapper

### PR DESCRIPTION
**Pull request by davidmerrique**
It doesn't pollute the window if using CommonJS/AMD and can be required like this:

```javascript
const ScrollTrigger = require('scrolltrigger-classes');
```

### CODE REVIEW

**Comment by johanneslamers** [comment]
Yes please!

**Comment by jlmakes** [comment]
I encountered some issues with a library of my own using a very similar UMD wrapper, where users attempting to minify using CodeKit were running into errors.

I recommend testing this change with CodeKit minification before merging. 🔑

**Comment by davidmerrique** [comment]
@jlmakes Just downloaded it and tried it, not getting any errors.

**Comment by terwanerik** [comment]
Nice one! I just updated to v0.3, if you could update this PR to the newest version that would be great, i'll merge it for sure then.

Thanks.

**Comment by davidmerrique** [comment]
@terwanerik Done!

What do you use to minify? I did this:

```
uglifyjs ScrollTrigger.js -m -o ScrollTrigger.min.js
```

I was going to suggest adding that as an npm script, but it turns out npm requires semantic versioning; `0.3` should be `0.3.0`
```json
"scripts": {
    "uglify": "uglifyjs ScrollTrigger.js -m -o ScrollTrigger.min.js"
}
```
Then you could `npm run uglify`

**Comment by terwanerik** [comment]
Thanks! Yeah the semantic versioning bug is now fixed with v0.3.1, should i change something in the package.json? I'm not really a NPM user ;)

**Comment by davidmerrique** [comment]
@terwanerik I think you just need to do an `npm publish` to get **v0.3.1** onto npm, it's still at **v0.2.6** there https://www.npmjs.com/package/scrolltrigger-classes. 

Thanks!

**Comment by terwanerik** [comment]
Cheers, keep on forgetting that. Done deal!

**Pull request merged**
